SuperMark/SuperMark/Models/ErrorViewModel.cs
using System;

namespace SuperMark.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SuperMark/SuperMark/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SuperMark.Models;

namespace SuperMark.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SuperMark/SuperMark/Controllers/ProductosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SuperMark.Data;
using SuperMark.Data.Entities;

namespace SuperMark.Controllers
{
    public class ProductosController : Controller
    {
        private readonly IProductosRepository productosRepository;
        private readonly ICategoriasRepository categoriasRepository;
        private readonly IMarcasRepository marcasRepository;

        public ProductosController(IProductosRepository productosRepository, ICategoriasRepository categoriasRepository, IMarcasRepository marcasRepository)
        {
            this.productosRepository = productosRepository;
            this.categoriasRepository = categoriasRepository;
            this.marcasRepository = marcasRepository;
        }

        // GET: Productos
        public async Task<IActionResult> Index()
        {
            return View(await productosRepository.GetAllProducts());
        }

        // GET: Productos/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tblProducto = await this.productosRepository.GetByIdAsync(id.Value);
            if (tblProducto == null)
            {
                return NotFound();
            }

            return View(tblProducto);
        }

        // GET: Productos/Create
        public IActionResult Create()
        {
            ViewBag.Categorias = new SelectList(this.categoriasRepository.GetAll().ToList(), "IdCategoria", "Nombre");
            ViewBag.Marcas = new SelectList(this.marcasRepository.GetAll().ToList(), "IdMarca", "Nombre");
            return View();
        }

 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(TblProducto tblProducto)
        {
            if (ModelState.IsValid)
            {
                await this.productosRepository.CreateAsync(tblProducto);
                return RedirectToAction(nameof(Index));
            }

            ViewBag.Categorias = new SelectList(this.categoriasRepository.GetAll().ToList(), "IdCategoria", "Nombre", tblProducto.IdCategoria);
            ViewBag.Marcas = new SelectList(this.marcasRepository.GetAll().ToList(), "IdMarca", "Nombre", tblProducto.IdCategoria);
            return View(tblProducto);
        }

        // GET: Productos/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tblProducto = await this.productosRepository.GetByIdAsync(id.Value);
            if (tblProducto == null)
            {
                return NotFound();
            }
            ViewBag.Categorias = new SelectList(this.categoriasRepository.GetAll().ToList(), "IdCategoria", "Nombre", tblProducto.IdCategoria);
            ViewBag.Marcas = new SelectList(this.marcasRepository.GetAll().ToList(), "IdMarca", "Nombre", tblProducto.IdMarca);

            return View(tblProducto);
        }

        // POST: Productos/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int? id, TblProducto tblProducto)
        {
            if (id != tblProducto.IdProducto)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await this.productosRepository.UpdateAsync(tblProducto);
                    
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (! await this.productosRepository.ExistAsync(tblProducto.IdProducto))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewBag.Categorias = new SelectList(this.categoriasRepository.GetAll().ToList(), "IdCategoria", "Nombre", tblProducto.IdCategoria);
            ViewBag.Marcas = new SelectList(this.marcasRepository.GetAll().ToList(), "IdMarca", "Nombre", tblProducto.IdMarca);
            
            return View(tblProducto);
        }

        // GET: Productos/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tblProducto = await this.productosRepository.GetByIdAsync(id.Value);
            if (tblProducto == null)
            {
                return NotFound();
            }

            return View(tblProducto);
        }

        // POST: Productos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tblProducto = await this.productosRepository.GetByIdAsync(id);
            await this.productosRepository.DeleteAsync(tblProducto);
           
            return RedirectToAction(nameof(Index));
        }

 
    }
}

SuperMark/SuperMark/Controllers/UsuariosController.cs
namespace SuperMark.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Helpers;

    public class UsuariosController : Controller
    {
        private readonly IUsuarioHelper userHelper;

        public UsuariosController(IUsuarioHelper userHelper)
        {
            this.userHelper = userHelper;
        }
        public async Task<IActionResult> Index()
        {
            return View(await this.userHelper.GetUsersAsync());
        }
    }
}

SuperMark/SuperMark/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

SuperMark/SuperMark/Views/Productos/Create.cshtml
@model SuperMark.Data.Entities.TblProducto

@{
    ViewData["Title"] = "Create";
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Productos</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a asp-action="Index">Productos</a></li>
                    <li class="breadcrumb-item active">Crear</li>
                </ol>
            </div>
        </div>
    </div>
</section>

<section class="content">
    <div class="row">
        <div class="col-12">
            <div class="card ">
                <div class="card-header">
                    <h3 class="card-title">Agregar Producto</h3>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-4">
                            <form asp-action="Create">
                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                <div class="form-group">
                                    <label asp-for="CodigoProducto" class="control-label"></label>
                                    <input asp-for="CodigoProducto" class="form-control" />
                                    <span asp-validation-for="CodigoProducto" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="NombreProducto" class="control-label"></label>
                                    <input asp-for="NombreProducto" class="form-control" />
                                    <span asp-validation-for="NombreProducto" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="IdMarca" class="control-label"></label>
                                    <select asp-for="IdMarca" class="form-control" asp-items="ViewBag.Marcas"></select>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Cantidad" class="control-label"></label>
                                    <input asp-for="Cantidad" class="form-control" />
                                    <span asp-validation-for="Cantidad" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="StockMinimo" class="control-label"></label>
                                    <input asp-for="StockMinimo" class="form-control" />
                                    <span asp-validation-for="StockMinimo" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="Costo" class="control-label"></label>
                                    <input asp-for="Costo" class="form-control" />
                                    <span asp-validation-for="Costo" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="PrecioNeto" class="control-label"></label>
                                    <input asp-for="PrecioNeto" class="form-control" />
                                    <span asp-validation-for="PrecioNeto" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="PrecioConsumidor" class="control-label"></label>
                                    <input asp-for="PrecioConsumidor" class="form-control" />
                                    <span asp-validation-for="PrecioConsumidor" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="PrecioDetalle" class="control-label"></label>
                                    <input asp-for="PrecioDetalle" class="form-control" />
                                    <span asp-validation-for="PrecioDetalle" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <label asp-for="IdCategoria" class="control-label"></label>
                                    <select asp-for="IdCategoria" class="form-control" asp-items="ViewBag.Categorias"></select>
                                </div>

                                <div class="form-group">
                                    <label asp-for="Estado" class="control-label"></label>
                                    <input asp-for="Estado" class="form-control" />
                                    <span asp-validation-for="Estado" class="text-danger"></span>
                                </div>
                                <div class="form-group">
                                    <input type="submit" value="Create" class="btn btn-primary" />
                                </div>
                            </form>
                        </div>
                    </div>

                    <div>
                        <a asp-action="Index">Back to List</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

SuperMark/SuperMark/Views/Productos/Delete.cshtml
@model SuperMark.Data.Entities.TblProducto

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TblProducto</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NombreProducto)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NombreProducto)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Cantidad)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Cantidad)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Costo)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Costo)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PrecioNeto)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PrecioNeto)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PrecioConsumidor)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PrecioConsumidor)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PrecioDetalle)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PrecioDetalle)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IdCategoriaNavigation)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdCategoriaNavigation.IdCategoria)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IdMarcaNavigation)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdMarcaNavigation.IdMarca)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdProducto" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SuperMark/SuperMark/Views/Productos/Details.cshtml
@model SuperMark.Data.Entities.TblProducto

@{
    ViewData["Title"] = "Details";
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>@Model.NombreProducto</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a asp-action="Index">Productos</a></li>
                    <li class="breadcrumb-item active">Detalle</li>
                </ol>
            </div>
        </div>
    </div>
</section>

<hr />
<section class="content">
    <div class="row">
        <div class="col-12">
            <div class="card ">
                <div class="card-header">
                    <h3 class="card-title">Detalle del producto</h3>
                </div>
                <div class="card-body ">
                    <dl class="row">
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.CodigoProducto)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.CodigoProducto)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.Cantidad)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.Cantidad)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.StockMinimo)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.StockMinimo)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.Costo)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.Costo)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.PrecioNeto)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.PrecioNeto)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.PrecioConsumidor)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.PrecioConsumidor)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.PrecioDetalle)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.PrecioDetalle)
                        </dd>

                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.Estado)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.Estado)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.IdCategoriaNavigation)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.IdCategoriaNavigation.IdCategoria)
                        </dd>
                        <dt class="col-sm-2">
                            @Html.DisplayNameFor(model => model.IdMarcaNavigation)
                        </dt>
                        <dd class="col-sm-10">
                            @Html.DisplayFor(model => model.IdMarcaNavigation.IdMarca)
                        </dd>
                    </dl>
                </div>
                <div>
                    <a asp-action="Edit" asp-route-id="@Model.IdProducto">Edit</a> |
                    <a asp-action="Index">Back to List</a>
                </div>
            </div>
        </div>
    </div>
</section>

SuperMark/SuperMark/Views/Productos/Edit.cshtml
@model SuperMark.Data.Entities.TblProducto

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>TblProducto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdProducto" />
            <div class="form-group">
                <label asp-for="NombreProducto" class="control-label"></label>
                <input asp-for="NombreProducto" class="form-control" />
                <span asp-validation-for="NombreProducto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CodigoProducto" class="control-label"></label>
                <input asp-for="CodigoProducto" class="form-control" />
                <span asp-validation-for="CodigoProducto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdMarca" class="control-label"></label>
                <select asp-for="IdMarca" class="form-control" asp-items="ViewBag.Marcas"></select>
                <span asp-validation-for="IdMarca" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Costo" class="control-label"></label>
                <input asp-for="Costo" class="form-control" />
                <span asp-validation-for="Costo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cantidad" class="control-label"></label>
                <input asp-for="Cantidad" class="form-control" />
                <span asp-validation-for="Cantidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="StockMinimo" class="control-label"></label>
                <input asp-for="StockMinimo" class="form-control" />
                <span asp-validation-for="StockMinimo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrecioNeto" class="control-label"></label>
                <input asp-for="PrecioNeto" class="form-control" />
                <span asp-validation-for="PrecioNeto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrecioConsumidor" class="control-label"></label>
                <input asp-for="PrecioConsumidor" class="form-control" />
                <span asp-validation-for="PrecioConsumidor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrecioDetalle" class="control-label"></label>
                <input asp-for="PrecioDetalle" class="form-control" />
                <span asp-validation-for="PrecioDetalle" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdCategoria" class="control-label"></label>
                <select asp-for="IdCategoria" class="form-control" asp-items="ViewBag.Categorias"></select>
                <span asp-validation-for="IdCategoria" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Estado" class="control-label"></label>
                <input asp-for="Estado" class="form-control" />
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

SuperMark/SuperMark/Views/Shared/_ControlSidebar.cshtml
<aside class="control-sidebar control-sidebar-dark">

</aside>

SuperMark/SuperMark/Views/Shared/_Footer.cshtml
<footer class="main-footer">
    <strong>Copyright ©  @DateTime.UtcNow.Year SuperMark.</strong>
    All rights reserved.
    <div class="float-right d-none d-sm-inline-block">
        <b>Version</b> Beta
    </div>
</footer>

SuperMark/SuperMark/Views/Shared/_Header.cshtml
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a asp-area="" class="nav-link" asp-controller="Home" asp-action="Index">
                Index
            </a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a asp-area="" class="nav-link" asp-controller="Home" asp-action="Privacy">
                Privacy
            </a>
        </li>
    </ul>

    <!-- SEARCH FORM -->
    <form class="form-inline ml-3">
        <div class="input-group input-group-sm">
            <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
            <div class="input-group-append">
                <button class="btn btn-navbar" type="submit">
                    <i class="fas fa-search"></i>
                </button>
            </div>
        </div>
    </form>

    <!-- Right navbar links -->
    <ul class="navbar-nav ml-auto">
       
        <!-- Notifications Dropdown Menu -->
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="far fa-bell"></i>
                
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                <span class="dropdown-item dropdown-header">Nada por aqui aun</span>
                <div class="dropdown-divider"></div>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#"><i class="fas fa-th-large"></i></a>
        </li>
    </ul>
</nav>

SuperMark/SuperMark/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es-sv">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>@ViewData["Title"] - SuperMark</title>
   
    <link href="~/lib/fontawesome-free/css/all.min.css" rel="stylesheet" />

    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">

    <link rel="stylesheet" href="~/css/site.css" />

    <link href="~/AdminLTE/dist/css/adminlte.css" rel="stylesheet" />

    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
</head>
<body class="hold-transition sidebar-mini" style="height: auto;">
    <div class="wrapper">
        <partial name="_Header.cshtml" />
        <partial name="_sidebar.cshtml" />
        <div class="content-wrapper">
                @RenderBody()
            @*<main role="main">
            </main>*@
        </div>
        <partial name="_ControlSidebar.cshtml" />
        <partial name="_Footer.cshtml" />
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/AdminLTE/dist/js/adminlte.js"></script>
    <script src="~/js/site.js"></script>


    @RenderSection("Scripts", required: false)
</body>
</html>

SuperMark/SuperMark/Views/Shared/_sidebar.cshtml
<aside class="main-sidebar sidebar-light-navy elevation-4 ">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
        <img src="~/Images/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
        <span class="brand-text font-weight-light">Administracion</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
        <!-- Sidebar user panel -->
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="~/Images/avatar5.png" class="img-circle elevation-2" alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block">User</a>
            </div>
        </div>

        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Add icons to the links using the .nav-icon class
    with font-awesome or any other icon font library -->
                <li class="nav-item has-treeview">
                    <a href="#" class="nav-link ">
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>
                            Panel
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a asp-area="" class="nav-link" asp-controller="Home" asp-action="Index">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Index</p>
                            </a>


                        </li>
                        <li class="nav-item">
                            <a asp-area="" class="nav-link" asp-controller="Home" asp-action="Privacy">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Privacy</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a asp-action="Index" asp-controller="Usuarios" class="nav-link">
                        <i class="nav-icon fas fa-user"></i>
                        <p>
                            Usuarios
                        </p>
                    </a>
                </li>
                
                <li class="nav-item has-treeview">
                    <a href="#" class="nav-link ">
                        <i class="nav-icon fas fa-box"></i>
                        <p>
                            Productos
                            <i class="right fas fa-angle-left"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a asp-area="" class="nav-link" asp-controller="Categorias" asp-action="Index">
                                <i class="far fa-circle nav-icon"></i>

                                <p>Categorias</p>

                            </a>


                        </li>
                        <li class="nav-item">
                            <a asp-area="" class="nav-link" asp-controller="Marcas" asp-action="Index">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Marcas</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="" class="nav-link" asp-controller="Productos" asp-action="Index">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Productos</p>
                            </a>
                        </li>
                    </ul>
                </li>

            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>